name: "macos"
on: [pull_request,workflow_dispatch]
jobs:
  build:
    name: "build"
    runs-on: macos-12
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build
